version: '3.8'
services:
  mysqldb:
    image: mysql:8.0.21
    ports:
      - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "device_shop"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_PASSWORD: "root"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      mysqldb:
        condition: service_completed_successfully
    environment:
      SPRING_APPLICATION_JSON: '{
           "spring.datasource.url"  : "jdbc:mysql://mysqldb:3307/device_shop?serverTimezone=UTC",
           "spring.datasource.username" : "root",
           "spring.datasource.password" : "root",
           "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5Dialect",
           "spring.jpa.hibernate.ddl-auto" : "update"
        }'