version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - localhost

  localhost:
    image: mysql:8.0.21
    ports:
      - "3306:3306"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/device_shop?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
  flyway:
        build:
          context: .
          dockerfile: Dockerfile.flyway
        depends_on:
          - localhost